[fly.app]
name = "crmp-bot"

[build]
builder = "heroku/buildpack:20"
command = "python main.py"

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[env]
# Переменные (токены) мы НЕ пишем здесь, а добавим позже в панели Fly.io
